### ISSUE TITLE
Schema inference

### ISSUE THREAD

**Issue by PaulBredl** [MetaConfigurator/meta-configurator#459]
Nice feature would be if the user is able to infer a schema from a json file

**Comment by PaulBredl** [comment]
@Logende meinst du das ist kein sinnvolles feature oder hast du das gemacht?

**Comment by Logende** [comment]
Ist erledigt.

wobei ich das Ticket vlt etwas vorschnell zugemacht habe weil es noch nicht im hauptrepo ist. Aber das plane ich morgen alles zu mergen und ab dann sauber alles auf diesem repo zu machen
